### PR TITLE
ABP support

### PR DESCRIPTION
**Pull request by lthiery**
Implements support for Activation by Personalization (ABP).

### CODE REVIEW

**Review by lulf — COMMENTED** [review]
Another approach could be to introduce a JoinMode enum (ABP, OTAA), did you consider it? Changes looks good, nice work!

**Comment by ivajloip** [comment]
This looks good indeed! I am also curious if there is a particular reason this approach was chosen over using a JoinMode enum as Ulf has suggested.

**Comment by lthiery** [comment]
I agree with the suggestion - I was hoping to fix it last week but things have gotten in they. Hoping to get to it soon!

**Comment by lthiery** [comment]
@ivajloip I implemented the enum and did some rebasing. Let me know if there's anything else!

**Comment by ivajloip** [comment]
Thank you so much, @lthiery !

**Pull request merged**
