### PR TITLE
standalone lora-modulation crate

### PR DESCRIPTION
**Pull request by lthiery**

### CODE REVIEW

**Review by lulf — COMMENTED** [review]
Looks good, but I'm wondering if this crate should ideally be placed in an organisation and a repository that can enjoy wider access to maintainers and reviewers? Also I think 'lora' is a too generic name, and something like 'lora-types' or 'lora-modulation' would be more appropriate.

**Comment by lthiery** [comment]
@ceekdee added you as a code maintainer to this module as well as added your bandwidth comment from #123

**Comment by lthiery** [comment]
@ivajloip we can give @ceekdee write access? i think the way you have it setup, it lets him push branches and review PRs within his code ownership purview?

**Review by ivajloip — APPROVED** [review]
I hope that's fine now.

**Comment by ivajloip** [comment]
and to answer @lulf, I think it could make sense to have an organization. Let's chat somewhere about how that could work (what's the ideal end state, how to get there, etc).

**Pull request merged**
