### PR TITLE
Add in github actions CI

### PR DESCRIPTION
**Pull request by lthiery**

### CODE REVIEW

**Review by ivajloip — APPROVED** [review]
I imagine we should provide the token somewhere in the settings of the project - I am checking that, but otherwise that looks good to me. Thanks! :)

**Comment by ivajloip** [comment]
From what I saw, the current settings should be fine for the actions to start running. Probably this code needs to be committed before we see the first runs (which makes sense I think).

**Review by lulf — COMMENTED** [review]
The job should probably build with the 'async' feature as well

**Comment by ivajloip** [comment]
> The job should probably build with the 'async' feature as well

That sounds as a good idea! Both addressed in this PR or in a separate one is fine for me.

**Pull request merged**
