### PR TITLE
Add checks permission on GITHUB_TOKEN

### PR DESCRIPTION
**Pull request by ivajloip**
This is expected to fix automated builds on master.

### CODE REVIEW

**Comment by lthiery** [comment]
image
something still ain't right

**Comment by lthiery** [comment]
image
Is there a panel in settings to control this? @ivajloip

**Comment by ivajloip** [comment]
I guess I finally figured the expected value out. Apologies for the noise! AFAIU the UI allows only to allow way too many things or only read permission for content (+metadata which apparently is there by default), both of which were not fine. I hope that's the only missing permission! :slightly_smiling_face:

**Comment by lthiery** [comment]
Give it a whirl on master then I guess!

**Review by lthiery — APPROVED** [review]

**Pull request merged**
