### PR TITLE
Switch to Const Generic for Transmit Buffer

### PR DESCRIPTION
**Pull request by lthiery**

### CODE REVIEW

**Review by lulf — APPROVED** [review]
You're forced to stack allocate the buffer with this change, but it a not that big of a problem now that the async impl is separate, and it's what I care about personally :)

**Comment by lthiery** [comment]
I personally don't see a major downside to that. Why would it be a problem in your view? Someone can always stuff it in an option if they want to put the whole Device struct in a static.

Maybe I'll work on another PR to make fn new a const.

**Comment by lthiery** [comment]
> Maybe I'll work on another PR to make fn new a const.

Ah - `trait bounds other than `Sized` on const fn parameters are unstable`. So I guess that's not an option for now

**Comment by lulf** [comment]
> I personally don't see a major downside to that. Why would it be a problem in your view? Someone can always stuff it in an option if they want to put the whole Device struct in a static.
> 

Yeah, that's certainly doable, so I wouldn't worry about it either.

> Maybe I'll work on another PR to make fn new a const.

One common approach is to use UnsafeCell or MaybeUninit for it, so I think it's fine without const new

**Pull request merged**
